### ISSUE TITLE
dat.sh broken with OSX utils

### ISSUE THREAD

**Issue by ralexstokes** [clojure-grimoire/grimoire#156]
When trying to compile docs locally via `make setup`, the execution of `dat.sh` fails due to an awk syntax error.  

```
awk: syntax error at source line 1
 context is
	 >>> {match($1,".*?:([^/]+)/.*", <<< 
awk: illegal statement at source line 1
awk: illegal statement at source line 1
```

Referring to the [OSX awk docs](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/awk.1.html), we see that triple arity match is not supported.  Is there a workaround for OSX awk that also works for other versions of awk?

A quick fix is `brew install gawk` and then `sed s/awk/gawk/`

**Comment by arrdem** [comment]
Patch proposed.
