### ISSUE TITLE
"catch" and "finally" links are broken

### ISSUE THREAD

**Issue by elarkin** [clojure-grimoire/grimoire#168]
They should point to http://conj.io/store/v0/org.clojure/clojure/1.7.0-alpha4/clj/clojure.core/try/ instead of http://conj.io/store/v0/org.clojure/clojure/1.7.0-alpha4/clj/clojure.core/catch and http://conj.io/store/v0/org.clojure/clojure/1.7.0-alpha4/clj/clojure.core/finally

**Comment by arrdem** [comment]
Huh. That should be hard-coded in, thanks I'll take a look at this.

**Comment by arrdem** [comment]
Found the issue. Looks like the latest generation of datafiles don't have the required redirect from `clojure.core/catch` and `clojure.core/finally` to `clojure.core/try`. WIP over on lein-grimoire

clojure-grimoire/lein-grim#7

**Comment by arrdem** [comment]
Live site should no longer have this issue. A "real" fix is incomming.
