### ISSUE TITLE
Take another swing at docstring formatting

### ISSUE THREAD

**Issue by arrdem** [clojure-grimoire/grimoire#174]
See http://conj.io/store/v0/org.clojure/clojure/1.6.0/clj/clojure.core/defn

Many of the docstrings in core get formatted like this, and it's a mess. Either I need a text flowing engine (doubtfull) or I need a formatting engine to normalize leading whitespace (likely) when rendering documentation.

**Comment by glenjamin** [comment]
HTML will handle reflows and normalise leading whitespace. What happens if you just don't use `<pre>` ?

**Comment by mavbozo** [comment]
this is what happens to http://conj.io/store/v0/org.clojure/clojure/1.6.0/clj/clojure.core/gen-class if you remove the `<pre>` tag

![gen-class](https://cloud.githubusercontent.com/assets/3253772/6901193/e1d34706-d735-11e4-8494-0c3c38547cbb.png)

**Comment by arrdem** [comment]
clojure.instant/parse-timestamp is similarly gawdawful

![2015-03-30-114716_1126x1057_scrot](https://cloud.githubusercontent.com/assets/704767/6901423/a1cf7872-d6d2-11e4-829b-17433319a14f.png)
