### ISSUE TITLE
Reformat the examples of defmulti

### ISSUE THREAD

**Issue by arrdem** [clojure-grimoire/grimoire#176]
Right now, these examples could use a fair bit of work. The banking software example especially is pretty bad.

**Comment by arrdem** [comment]
https://github.com/clojure-grimoire/doc-clojure-core/tree/master/org.clojure/clojure/1.4.0/clj/clojure.core/defmulti/examples is the examples in question

**Comment by noisesmith** [comment]
I'm taking a go at this.
