### ISSUE TITLE
'catch' and 'finally' links broken

### ISSUE THREAD

**Issue by austinzheng** [clojure-grimoire/grimoire#184]
Clicking on the `catch` or `finally` links under Exceptions results in a page with the error message: `Unknown symbol identifier`.

Relevant links are:

- http://conj.io/store/v0/org.clojure/clojure/1.7.0-alpha4/clj/clojure.core/catch
- http://conj.io/store/v0/org.clojure/clojure/1.7.0-alpha4/clj/clojure.core/finally

**Comment by arrdem** [comment]
Yep. Known issue. This should get fixed when I drop the next release in ~72hrs.
