### ISSUE TITLE
New vars in Clojure 1.7.0 have links but no page content

### ISSUE THREAD

**Issue by jafingerhut** [clojure-grimoire/grimoire#209]
At least this one does not: http://conj.io/store/v1/org.clojure/clojure/1.7.0-alpha4/clj/clojure.core/update

I did not check them all.

**Comment by arrdem** [comment]
Yeah I noticed this after you announced the 1.7 cheat sheet. I'll try and debug it tomorrow. Thanks for the issue.

**Comment by arrdem** [comment]
Taking a look at this now... my gut looking at the data storage structure is that either the lib-grimoire engine isn't dealing with missing notes or missing example dirs correctly.
