### ISSUE TITLE
No content for `throw` function 

### ISSUE THREAD

**Issue by timgluz** [clojure-grimoire/grimoire#213]
When i was looking for documentation about `throw` function, it  showed me text "unknown symbol" and on the link with text `github bugtracker` misses href attribute. 

![screenshot 2015-07-15 18 20 40](https://cloud.githubusercontent.com/assets/1223889/8703698/f023e7c4-2b1e-11e5-8a99-b2f6ddc5a7d5.png)

**Comment by jafingerhut** [comment]
Similarly for most of the symbols in the "Special Forms" section of the cheat sheet: http://jafingerhut.github.io/cheatsheet/grimoire/cheatsheet-tiptip-cdocs-summary.html

(about half way down in the right column, or search for any of them, e.g. throw, in the top search box to make it one of the only things visible)

Those are not really functions, but special symbols in Clojure.

**Comment by arrdem** [comment]
Noted. Thanks guys I'll try and get this fixed ASAP.

**Comment by arrdem** [comment]
Right ok so this is the product of changes to the lein-grim program in support of being less hardwired to clojure/core. I need to write up a datafile with docs for the special forms to deal with the fact that special forms don't actually exist as defs with metadata from which docs can be introspected. Previously I tied the doc generation pipeline to clojure.repl's doc implementation which happens to include baked in text for all the special forms but that doesn't scale and I figured it made sense to expect users (myself included) to provide a mapping file describing the special forms in their particular doc set/use case.

**Comment by arrdem** [comment]
Taking a crack at this now since @j-po bumped it.
