### ISSUE TITLE
Missing docs for if and recur (1.7.0)

### ISSUE THREAD

**Issue by j-po** [clojure-grimoire/grimoire#214]
[if](http://conj.io/store/v1/org.clojure/clojure/1.7.0/clj/clojure.core/if/) and [recur](http://conj.io/store/v1/org.clojure/clojure/1.7.0/clj/clojure.core/recur/). All seems to be well with respect to these pages for 1.6.

**Comment by arrdem** [comment]
Same issue as #213 tracking there.
