### ISSUE TITLE
`letfn` link broken

### ISSUE THREAD

**Issue by amithgeorge** [clojure-grimoire/grimoire#215]
The `letfn` link on the page http://jafingerhut.github.io/cheatsheet/grimoire/cheatsheet-tiptip-cdocs-summary.html points to http://conj.io/store/v0/org.clojure/clojure/latest/clj/clojure.core/letfn/. That page redirects to http://conj.io/store/v1/org.clojure/clojure/1.7.0-alpha4/clj/clojure.core/letfn. Which shows the error message 

   > Unknown symbol identifier "clojure.core/letfn"
   > If you found a broken link, please report the issue encountered on the github bugtracker.

For reference, http://conj.io/store/v1/org.clojure/clojure/1.7.0/clj/clojure.core/letfn is a valid documentation page.

**Comment by jafingerhut** [comment]
Strange, I do not see a broken link there, but a normal-looking Grimoire page describing letfn.  It does not go to a link with 1.7.0-alpha4 in it, but 1.7.0.  Perhaps it has been fixed already on the server between report time and now?

**Comment by arrdem** [comment]
This is a client side caching issue in your browser. The `/latest/` segment fires a 30X redirect to rewrite itself to the newest version of Clojure documented here, presently `1.7.0`. There was for a while `1.7.0-ALPHAN` data here as well. I suspect what's happening is that your browser has cached the redirect to now nonexistant content. That I'm issuing a redirect code which is cachable is arguably a bug and I'll look into but this is mainly a browser issue on your end :cry:

**Comment by amithgeorge** [comment]
@arrdem, yup. Cleared the cache and the link works properly. Google tells me that the options seem to be either use 301 with a short enough cache duration header, or use a 307 which supposedly doesn't get cached by default. As you are already aware of the root cause (and its fixed atleast for me for the time being), I guess this issue can be closed?

**Comment by arrdem** [comment]
Okay I'll put in a patch to return 307s when I get a minute. Leaving this open 'til then.
