### ISSUE TITLE
Unknown symbol identifier "clojure.core/try" (throw try catch finally set! . new)

### ISSUE THREAD

**Issue by keyber** [clojure-grimoire/grimoire#266]
from this page https://www.conj.io/
in the Java Interoperation (clojure.org/java_interop) box, 
sevral links lead to this message :
"Unknown symbol identifier "clojure.core/try" If you found a broken link, please report the issue encountered on the github bugtracker."
here is the list :
throw try catch finally set! . new

**Comment by arrdem** [comment]
Huh. These were definitely documented at one point - Clojure has some baked-in magic for documenting "special forms" to cover these cases but looking in the data store I can confirm that there isn't backing information for these forms right now.

**Comment by arrdem** [comment]
Fixed. Sorry about that, thanks for the report!
